// This file was auto-generated by Fern from our API Definition.

export interface NextVisiblePassResponse {
    azimuthDeg: number;
    elevationDeg: number;
    passTime: string;
    rangeKm: number;
    satelliteId: string;
    satelliteName: string;
}
