// This file was auto-generated by Fern from our API Definition.

import type * as SatelliteApiApi from "../index.js";

export interface OverheadResponse {
    elevation: number;
    satellite: SatelliteApiApi.Satellite;
}
