// This file was auto-generated by Fern from our API Definition.

import type * as SatelliteApiApi from "../index.js";

/**
 * Generic Paginated Response envelope
 */
export interface PaginatedResponseSatellite {
    data: SatelliteApiApi.Satellite[];
    pagination: SatelliteApiApi.PaginationMeta;
}
