// This file was auto-generated by Fern from our API Definition.

/**
 * Metadata envelope for paginated responses
 */
export interface PaginationMeta {
    hasMore: boolean;
    limit: number;
    nextCursor?: (string | null) | undefined;
    totalCount: number;
}
