// This file was auto-generated by Fern from our API Definition.

import type * as SatelliteApiApi from "../index.js";

export interface Satellite {
    createdDate: string;
    id: string;
    lastModifiedDate: string;
    name: string;
    tle: SatelliteApiApi.Tle;
}
