// Code generated by Fern. DO NOT EDIT.

package client

import (
	astrodynamics "sdk/astrodynamics"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
	pipelines "sdk/pipelines"
	satellites "sdk/satellites"
)

type Client struct {
	Astrodynamics *astrodynamics.Client
	Pipelines     *pipelines.Client
	Satellites    *satellites.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Astrodynamics: astrodynamics.NewClient(options),
		Pipelines:     pipelines.NewClient(options),
		Satellites:    satellites.NewClient(options),
		options:       options,
		baseURL:       options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
