# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        ErrorResponse,
        NextVisiblePassResponse,
        OverheadResponse,
        PaginatedResponseSatellite,
        PaginationMeta,
        PipelineSyncResponse,
        Satellite,
        Tle,
    )
    from .errors import BadRequestError, InternalServerError, NotFoundError
    from . import astrodynamics, pipelines, satellites
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AsyncSatelliteApiApi, SatelliteApiApi
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncSatelliteApiApi": ".client",
    "BadRequestError": ".errors",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ErrorResponse": ".types",
    "InternalServerError": ".errors",
    "NextVisiblePassResponse": ".types",
    "NotFoundError": ".errors",
    "OverheadResponse": ".types",
    "PaginatedResponseSatellite": ".types",
    "PaginationMeta": ".types",
    "PipelineSyncResponse": ".types",
    "Satellite": ".types",
    "SatelliteApiApi": ".client",
    "Tle": ".types",
    "astrodynamics": ".astrodynamics",
    "pipelines": ".pipelines",
    "satellites": ".satellites",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncSatelliteApiApi",
    "BadRequestError",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ErrorResponse",
    "InternalServerError",
    "NextVisiblePassResponse",
    "NotFoundError",
    "OverheadResponse",
    "PaginatedResponseSatellite",
    "PaginationMeta",
    "PipelineSyncResponse",
    "Satellite",
    "SatelliteApiApi",
    "Tle",
    "astrodynamics",
    "pipelines",
    "satellites",
]
