// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as SatelliteApiApi from "../index.js";

export class NotFoundError extends errors.SatelliteApiApiError {
    public declare readonly body: SatelliteApiApi.ErrorResponse;

    constructor(body: SatelliteApiApi.ErrorResponse, rawResponse?: core.RawResponse) {
        super({
            message: "NotFoundError",
            statusCode: 404,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = "NotFoundError";
    }
}
