blank_issues_enabled: false
contact_links:
  - name: 💬 Astrea SDA API Discussions
    url: https://github.com/mgwedd/astrea-sda-api/discussions
    about: Ask questions, share ideas, and discuss astrodynamics architecture.
