// Code generated by Fern. DO NOT EDIT.

package satellites

import (
	context "context"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Retrieves a paginated list of satellites using base64 checkpoint cursors.
//
// Example:
//
//	request := &sdk.ListSatellitesRequest{}
//	client.Satellites.ListSatellites(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListSatellites(
	ctx context.Context,
	request *sdk.ListSatellitesRequest,
	opts ...option.RequestOption,
) (*sdk.PaginatedResponseSatellite, error) {
	response, err := c.WithRawResponse.ListSatellites(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new satellite record from Two-Line Element (TLE) set data.
//
// Example:
//
//	request := &sdk.CreateSatelliteDto{
//	    LineOne: "lineOne",
//	    LineTwo: "lineTwo",
//	    Name: "name",
//	}
//	client.Satellites.CreateSatellite(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateSatellite(
	ctx context.Context,
	request *sdk.CreateSatelliteDto,
	opts ...option.RequestOption,
) (*sdk.Satellite, error) {
	response, err := c.WithRawResponse.CreateSatellite(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves details for a specific satellite by its unique UUID.
//
// Example:
//
//	request := &sdk.GetSatelliteRequest{
//	    ID: "id",
//	}
//	client.Satellites.GetSatellite(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetSatellite(
	ctx context.Context,
	request *sdk.GetSatelliteRequest,
	opts ...option.RequestOption,
) (*sdk.Satellite, error) {
	response, err := c.WithRawResponse.GetSatellite(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes a satellite record by its unique UUID.
//
// Example:
//
//	request := &sdk.DeleteSatelliteRequest{
//	    ID: "id",
//	}
//	client.Satellites.DeleteSatellite(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteSatellite(
	ctx context.Context,
	request *sdk.DeleteSatelliteRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteSatellite(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Updates a satellite's name or TLE orbital parameters.
//
// Example:
//
//	request := &sdk.UpdateSatelliteDto{
//	    ID: "id",
//	}
//	client.Satellites.UpdateSatellite(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateSatellite(
	ctx context.Context,
	request *sdk.UpdateSatelliteDto,
	opts ...option.RequestOption,
) (*sdk.Satellite, error) {
	response, err := c.WithRawResponse.UpdateSatellite(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
