// This file was auto-generated by Fern from our API Definition.

import { AstrodynamicsClient } from "./api/resources/astrodynamics/client/Client.js";
import { PipelinesClient } from "./api/resources/pipelines/client/Client.js";
import { SatellitesClient } from "./api/resources/satellites/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace SatelliteApiApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SatelliteApiApiClient {
    protected readonly _options: NormalizedClientOptions<SatelliteApiApiClient.Options>;
    protected _astrodynamics: AstrodynamicsClient | undefined;
    protected _pipelines: PipelinesClient | undefined;
    protected _satellites: SatellitesClient | undefined;

    constructor(options: SatelliteApiApiClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get astrodynamics(): AstrodynamicsClient {
        return (this._astrodynamics ??= new AstrodynamicsClient(this._options));
    }

    public get pipelines(): PipelinesClient {
        return (this._pipelines ??= new PipelinesClient(this._options));
    }

    public get satellites(): SatellitesClient {
        return (this._satellites ??= new SatellitesClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
            },
            requestOptions,
        );
    }
}
