# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .error_response import ErrorResponse
    from .next_visible_pass_response import NextVisiblePassResponse
    from .overhead_response import OverheadResponse
    from .paginated_response_satellite import PaginatedResponseSatellite
    from .pagination_meta import PaginationMeta
    from .pipeline_sync_response import PipelineSyncResponse
    from .satellite import Satellite
    from .tle import Tle
_dynamic_imports: typing.Dict[str, str] = {
    "ErrorResponse": ".error_response",
    "NextVisiblePassResponse": ".next_visible_pass_response",
    "OverheadResponse": ".overhead_response",
    "PaginatedResponseSatellite": ".paginated_response_satellite",
    "PaginationMeta": ".pagination_meta",
    "PipelineSyncResponse": ".pipeline_sync_response",
    "Satellite": ".satellite",
    "Tle": ".tle",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ErrorResponse",
    "NextVisiblePassResponse",
    "OverheadResponse",
    "PaginatedResponseSatellite",
    "PaginationMeta",
    "PipelineSyncResponse",
    "Satellite",
    "Tle",
]
