# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class NextVisiblePassResponse(UniversalBaseModel):
    azimuth_deg: typing_extensions.Annotated[
        float, FieldMetadata(alias="azimuthDeg"), pydantic.Field(alias="azimuthDeg")
    ]
    elevation_deg: typing_extensions.Annotated[
        float, FieldMetadata(alias="elevationDeg"), pydantic.Field(alias="elevationDeg")
    ]
    pass_time: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="passTime"), pydantic.Field(alias="passTime")
    ]
    range_km: typing_extensions.Annotated[float, FieldMetadata(alias="rangeKm"), pydantic.Field(alias="rangeKm")]
    satellite_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="satelliteId"), pydantic.Field(alias="satelliteId")
    ]
    satellite_name: typing_extensions.Annotated[
        str, FieldMetadata(alias="satelliteName"), pydantic.Field(alias="satelliteName")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
