# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .tle import Tle


class Satellite(UniversalBaseModel):
    created_date: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdDate"), pydantic.Field(alias="createdDate")
    ]
    id: str
    last_modified_date: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="lastModifiedDate"), pydantic.Field(alias="lastModifiedDate")
    ]
    name: str
    tle: Tle

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
