# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.pipeline_sync_response import PipelineSyncResponse
from .raw_client import AsyncRawPipelinesClient, RawPipelinesClient


class PipelinesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPipelinesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPipelinesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPipelinesClient
        """
        return self._raw_client

    def trigger_pipeline_sync(
        self, *, group: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> PipelineSyncResponse:
        """
        Triggers automated CelesTrak discovery pipeline synchronization for a specific satellite group.

        Parameters
        ----------
        group : typing.Optional[str]
            CelesTrak satellite group name (e.g. 'stations', 'visual', 'starlink', 'weather', 'active', 'last-30-days')

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineSyncResponse
            Pipeline sync completed successfully

        Examples
        --------
        from satellite_api import SatelliteApiApi

        client = SatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.pipelines.trigger_pipeline_sync()
        """
        _response = self._raw_client.trigger_pipeline_sync(group=group, request_options=request_options)
        return _response.data


class AsyncPipelinesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPipelinesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPipelinesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPipelinesClient
        """
        return self._raw_client

    async def trigger_pipeline_sync(
        self, *, group: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> PipelineSyncResponse:
        """
        Triggers automated CelesTrak discovery pipeline synchronization for a specific satellite group.

        Parameters
        ----------
        group : typing.Optional[str]
            CelesTrak satellite group name (e.g. 'stations', 'visual', 'starlink', 'weather', 'active', 'last-30-days')

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PipelineSyncResponse
            Pipeline sync completed successfully

        Examples
        --------
        import asyncio

        from satellite_api import AsyncSatelliteApiApi

        client = AsyncSatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.pipelines.trigger_pipeline_sync()


        asyncio.run(main())
        """
        _response = await self._raw_client.trigger_pipeline_sync(group=group, request_options=request_options)
        return _response.data
