// Code generated by Fern. DO NOT EDIT.

package pipelines

import (
	context "context"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Triggers automated CelesTrak discovery pipeline synchronization for a specific satellite group.
//
// Example:
//
//	request := &sdk.TriggerPipelineSyncRequest{}
//	client.Pipelines.TriggerPipelineSync(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) TriggerPipelineSync(
	ctx context.Context,
	request *sdk.TriggerPipelineSyncRequest,
	opts ...option.RequestOption,
) (*sdk.PipelineSyncResponse, error) {
	response, err := c.WithRawResponse.TriggerPipelineSync(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
