// Code generated by Fern. DO NOT EDIT.

package astrodynamics

import (
	context "context"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Computes the satellite closest to overhead (highest elevation) across all tracked satellites using parallel Rayon propagation.
//
// Example:
//
//	request := &sdk.GetOverheadSatelliteRequest{
//	    Lat: 1.1,
//	    Lon: 1.1,
//	}
//	client.Astrodynamics.GetOverheadSatellite(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetOverheadSatellite(
	ctx context.Context,
	request *sdk.GetOverheadSatelliteRequest,
	opts ...option.RequestOption,
) (*sdk.OverheadResponse, error) {
	response, err := c.WithRawResponse.GetOverheadSatellite(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Calculates the next visible pass for a specific satellite above elevation threshold.
//
// Example:
//
//	request := &sdk.GetNextVisiblePassRequest{
//	    ID: "id",
//	    Lat: 1.1,
//	    Lon: 1.1,
//	}
//	client.Astrodynamics.GetNextVisiblePass(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetNextVisiblePass(
	ctx context.Context,
	request *sdk.GetNextVisiblePassRequest,
	opts ...option.RequestOption,
) (*sdk.NextVisiblePassResponse, error) {
	response, err := c.WithRawResponse.GetNextVisiblePass(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
