// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersGetNextVisiblePassRequest(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &GetNextVisiblePassRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLat", func(t *testing.T) {
		obj := &GetNextVisiblePassRequest{}
		var fernTestValueLat float64
		obj.SetLat(fernTestValueLat)
		assert.Equal(t, fernTestValueLat, obj.Lat)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLon", func(t *testing.T) {
		obj := &GetNextVisiblePassRequest{}
		var fernTestValueLon float64
		obj.SetLon(fernTestValueLon)
		assert.Equal(t, fernTestValueLon, obj.Lon)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAlt", func(t *testing.T) {
		obj := &GetNextVisiblePassRequest{}
		var fernTestValueAlt *float64
		obj.SetAlt(fernTestValueAlt)
		assert.Equal(t, fernTestValueAlt, obj.Alt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetThresholdDeg", func(t *testing.T) {
		obj := &GetNextVisiblePassRequest{}
		var fernTestValueThresholdDeg *float64
		obj.SetThresholdDeg(fernTestValueThresholdDeg)
		assert.Equal(t, fernTestValueThresholdDeg, obj.ThresholdDeg)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetNextVisiblePassRequest(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetNextVisiblePassRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLat_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetNextVisiblePassRequest{}
		var fernTestValueLat float64

		// Act
		obj.SetLat(fernTestValueLat)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLon_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetNextVisiblePassRequest{}
		var fernTestValueLon float64

		// Act
		obj.SetLon(fernTestValueLon)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAlt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetNextVisiblePassRequest{}
		var fernTestValueAlt *float64

		// Act
		obj.SetAlt(fernTestValueAlt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetThresholdDeg_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetNextVisiblePassRequest{}
		var fernTestValueThresholdDeg *float64

		// Act
		obj.SetThresholdDeg(fernTestValueThresholdDeg)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetOverheadSatelliteRequest(t *testing.T) {
	t.Run("SetLat", func(t *testing.T) {
		obj := &GetOverheadSatelliteRequest{}
		var fernTestValueLat float64
		obj.SetLat(fernTestValueLat)
		assert.Equal(t, fernTestValueLat, obj.Lat)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLon", func(t *testing.T) {
		obj := &GetOverheadSatelliteRequest{}
		var fernTestValueLon float64
		obj.SetLon(fernTestValueLon)
		assert.Equal(t, fernTestValueLon, obj.Lon)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAlt", func(t *testing.T) {
		obj := &GetOverheadSatelliteRequest{}
		var fernTestValueAlt *float64
		obj.SetAlt(fernTestValueAlt)
		assert.Equal(t, fernTestValueAlt, obj.Alt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTime", func(t *testing.T) {
		obj := &GetOverheadSatelliteRequest{}
		var fernTestValueTime *time.Time
		obj.SetTime(fernTestValueTime)
		assert.Equal(t, fernTestValueTime, obj.Time)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetOverheadSatelliteRequest(t *testing.T) {
	t.Run("SetLat_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetOverheadSatelliteRequest{}
		var fernTestValueLat float64

		// Act
		obj.SetLat(fernTestValueLat)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLon_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetOverheadSatelliteRequest{}
		var fernTestValueLon float64

		// Act
		obj.SetLon(fernTestValueLon)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAlt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetOverheadSatelliteRequest{}
		var fernTestValueAlt *float64

		// Act
		obj.SetAlt(fernTestValueAlt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTime_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetOverheadSatelliteRequest{}
		var fernTestValueTime *time.Time

		// Act
		obj.SetTime(fernTestValueTime)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersNextVisiblePassResponse(t *testing.T) {
	t.Run("SetAzimuthDeg", func(t *testing.T) {
		obj := &NextVisiblePassResponse{}
		var fernTestValueAzimuthDeg float64
		obj.SetAzimuthDeg(fernTestValueAzimuthDeg)
		assert.Equal(t, fernTestValueAzimuthDeg, obj.AzimuthDeg)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetElevationDeg", func(t *testing.T) {
		obj := &NextVisiblePassResponse{}
		var fernTestValueElevationDeg float64
		obj.SetElevationDeg(fernTestValueElevationDeg)
		assert.Equal(t, fernTestValueElevationDeg, obj.ElevationDeg)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPassTime", func(t *testing.T) {
		obj := &NextVisiblePassResponse{}
		var fernTestValuePassTime time.Time
		obj.SetPassTime(fernTestValuePassTime)
		assert.Equal(t, fernTestValuePassTime, obj.PassTime)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRangeKm", func(t *testing.T) {
		obj := &NextVisiblePassResponse{}
		var fernTestValueRangeKm float64
		obj.SetRangeKm(fernTestValueRangeKm)
		assert.Equal(t, fernTestValueRangeKm, obj.RangeKm)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSatelliteID", func(t *testing.T) {
		obj := &NextVisiblePassResponse{}
		var fernTestValueSatelliteID string
		obj.SetSatelliteID(fernTestValueSatelliteID)
		assert.Equal(t, fernTestValueSatelliteID, obj.SatelliteID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSatelliteName", func(t *testing.T) {
		obj := &NextVisiblePassResponse{}
		var fernTestValueSatelliteName string
		obj.SetSatelliteName(fernTestValueSatelliteName)
		assert.Equal(t, fernTestValueSatelliteName, obj.SatelliteName)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersNextVisiblePassResponse(t *testing.T) {
	t.Run("GetAzimuthDeg", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NextVisiblePassResponse{}
		var expected float64
		obj.AzimuthDeg = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAzimuthDeg(), "getter should return the property value")
	})

	t.Run("GetAzimuthDeg_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NextVisiblePassResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAzimuthDeg() // Should return zero value
	})

	t.Run("GetElevationDeg", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NextVisiblePassResponse{}
		var expected float64
		obj.ElevationDeg = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetElevationDeg(), "getter should return the property value")
	})

	t.Run("GetElevationDeg_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NextVisiblePassResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetElevationDeg() // Should return zero value
	})

	t.Run("GetPassTime", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NextVisiblePassResponse{}
		var expected time.Time
		obj.PassTime = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPassTime(), "getter should return the property value")
	})

	t.Run("GetPassTime_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NextVisiblePassResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPassTime() // Should return zero value
	})

	t.Run("GetRangeKm", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NextVisiblePassResponse{}
		var expected float64
		obj.RangeKm = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRangeKm(), "getter should return the property value")
	})

	t.Run("GetRangeKm_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NextVisiblePassResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRangeKm() // Should return zero value
	})

	t.Run("GetSatelliteID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NextVisiblePassResponse{}
		var expected string
		obj.SatelliteID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSatelliteID(), "getter should return the property value")
	})

	t.Run("GetSatelliteID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NextVisiblePassResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSatelliteID() // Should return zero value
	})

	t.Run("GetSatelliteName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NextVisiblePassResponse{}
		var expected string
		obj.SatelliteName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSatelliteName(), "getter should return the property value")
	})

	t.Run("GetSatelliteName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NextVisiblePassResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSatelliteName() // Should return zero value
	})

}

func TestSettersMarkExplicitNextVisiblePassResponse(t *testing.T) {
	t.Run("SetAzimuthDeg_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NextVisiblePassResponse{}
		var fernTestValueAzimuthDeg float64

		// Act
		obj.SetAzimuthDeg(fernTestValueAzimuthDeg)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetElevationDeg_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NextVisiblePassResponse{}
		var fernTestValueElevationDeg float64

		// Act
		obj.SetElevationDeg(fernTestValueElevationDeg)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPassTime_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NextVisiblePassResponse{}
		var fernTestValuePassTime time.Time

		// Act
		obj.SetPassTime(fernTestValuePassTime)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRangeKm_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NextVisiblePassResponse{}
		var fernTestValueRangeKm float64

		// Act
		obj.SetRangeKm(fernTestValueRangeKm)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSatelliteID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NextVisiblePassResponse{}
		var fernTestValueSatelliteID string

		// Act
		obj.SetSatelliteID(fernTestValueSatelliteID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSatelliteName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NextVisiblePassResponse{}
		var fernTestValueSatelliteName string

		// Act
		obj.SetSatelliteName(fernTestValueSatelliteName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersOverheadResponse(t *testing.T) {
	t.Run("SetElevation", func(t *testing.T) {
		obj := &OverheadResponse{}
		var fernTestValueElevation float64
		obj.SetElevation(fernTestValueElevation)
		assert.Equal(t, fernTestValueElevation, obj.Elevation)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSatellite", func(t *testing.T) {
		obj := &OverheadResponse{}
		var fernTestValueSatellite *Satellite
		obj.SetSatellite(fernTestValueSatellite)
		assert.Equal(t, fernTestValueSatellite, obj.Satellite)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersOverheadResponse(t *testing.T) {
	t.Run("GetElevation", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OverheadResponse{}
		var expected float64
		obj.Elevation = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetElevation(), "getter should return the property value")
	})

	t.Run("GetElevation_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OverheadResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetElevation() // Should return zero value
	})

	t.Run("GetSatellite", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OverheadResponse{}
		var expected *Satellite
		obj.Satellite = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSatellite(), "getter should return the property value")
	})

	t.Run("GetSatellite_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OverheadResponse{}
		obj.Satellite = nil

		// Act & Assert
		assert.Nil(t, obj.GetSatellite(), "getter should return nil when property is nil")
	})

	t.Run("GetSatellite_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OverheadResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSatellite() // Should return zero value
	})

}

func TestSettersMarkExplicitOverheadResponse(t *testing.T) {
	t.Run("SetElevation_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OverheadResponse{}
		var fernTestValueElevation float64

		// Act
		obj.SetElevation(fernTestValueElevation)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSatellite_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OverheadResponse{}
		var fernTestValueSatellite *Satellite

		// Act
		obj.SetSatellite(fernTestValueSatellite)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingNextVisiblePassResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NextVisiblePassResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled NextVisiblePassResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj NextVisiblePassResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj NextVisiblePassResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingOverheadResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &OverheadResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled OverheadResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj OverheadResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj OverheadResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringNextVisiblePassResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &NextVisiblePassResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NextVisiblePassResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringOverheadResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &OverheadResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OverheadResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesNextVisiblePassResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &NextVisiblePassResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NextVisiblePassResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesOverheadResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &OverheadResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *OverheadResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
