// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
	time "time"
)

var (
	getNextVisiblePassRequestFieldID           = big.NewInt(1 << 0)
	getNextVisiblePassRequestFieldLat          = big.NewInt(1 << 1)
	getNextVisiblePassRequestFieldLon          = big.NewInt(1 << 2)
	getNextVisiblePassRequestFieldAlt          = big.NewInt(1 << 3)
	getNextVisiblePassRequestFieldThresholdDeg = big.NewInt(1 << 4)
)

type GetNextVisiblePassRequest struct {
	// Satellite unique UUID identifier
	ID string `json:"-" url:"-"`
	// Observer latitude in decimal degrees (-90.0 to 90.0)
	Lat float64 `json:"-" url:"lat"`
	// Observer longitude in decimal degrees (-180.0 to 180.0)
	Lon float64 `json:"-" url:"lon"`
	// Observer altitude above sea level in meters
	Alt *float64 `json:"-" url:"alt,omitempty"`
	// Minimum elevation angle threshold in degrees (default: 5.0 deg)
	ThresholdDeg *float64 `json:"-" url:"threshold_deg,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetNextVisiblePassRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNextVisiblePassRequest) SetID(id string) {
	g.ID = id
	g.require(getNextVisiblePassRequestFieldID)
}

// SetLat sets the Lat field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNextVisiblePassRequest) SetLat(lat float64) {
	g.Lat = lat
	g.require(getNextVisiblePassRequestFieldLat)
}

// SetLon sets the Lon field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNextVisiblePassRequest) SetLon(lon float64) {
	g.Lon = lon
	g.require(getNextVisiblePassRequestFieldLon)
}

// SetAlt sets the Alt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNextVisiblePassRequest) SetAlt(alt *float64) {
	g.Alt = alt
	g.require(getNextVisiblePassRequestFieldAlt)
}

// SetThresholdDeg sets the ThresholdDeg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNextVisiblePassRequest) SetThresholdDeg(thresholdDeg *float64) {
	g.ThresholdDeg = thresholdDeg
	g.require(getNextVisiblePassRequestFieldThresholdDeg)
}

var (
	getOverheadSatelliteRequestFieldLat  = big.NewInt(1 << 0)
	getOverheadSatelliteRequestFieldLon  = big.NewInt(1 << 1)
	getOverheadSatelliteRequestFieldAlt  = big.NewInt(1 << 2)
	getOverheadSatelliteRequestFieldTime = big.NewInt(1 << 3)
)

type GetOverheadSatelliteRequest struct {
	// Observer latitude in decimal degrees (-90.0 to 90.0)
	Lat float64 `json:"-" url:"lat"`
	// Observer longitude in decimal degrees (-180.0 to 180.0)
	Lon float64 `json:"-" url:"lon"`
	// Observer altitude above sea level in meters
	Alt *float64 `json:"-" url:"alt,omitempty"`
	// UTC timestamp for calculation epoch (defaults to current time if omitted)
	Time *time.Time `json:"-" url:"time,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetOverheadSatelliteRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetLat sets the Lat field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOverheadSatelliteRequest) SetLat(lat float64) {
	g.Lat = lat
	g.require(getOverheadSatelliteRequestFieldLat)
}

// SetLon sets the Lon field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOverheadSatelliteRequest) SetLon(lon float64) {
	g.Lon = lon
	g.require(getOverheadSatelliteRequestFieldLon)
}

// SetAlt sets the Alt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOverheadSatelliteRequest) SetAlt(alt *float64) {
	g.Alt = alt
	g.require(getOverheadSatelliteRequestFieldAlt)
}

// SetTime sets the Time field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOverheadSatelliteRequest) SetTime(time *time.Time) {
	g.Time = time
	g.require(getOverheadSatelliteRequestFieldTime)
}

var (
	nextVisiblePassResponseFieldAzimuthDeg    = big.NewInt(1 << 0)
	nextVisiblePassResponseFieldElevationDeg  = big.NewInt(1 << 1)
	nextVisiblePassResponseFieldPassTime      = big.NewInt(1 << 2)
	nextVisiblePassResponseFieldRangeKm       = big.NewInt(1 << 3)
	nextVisiblePassResponseFieldSatelliteID   = big.NewInt(1 << 4)
	nextVisiblePassResponseFieldSatelliteName = big.NewInt(1 << 5)
)

type NextVisiblePassResponse struct {
	AzimuthDeg    float64   `json:"azimuthDeg" url:"azimuthDeg"`
	ElevationDeg  float64   `json:"elevationDeg" url:"elevationDeg"`
	PassTime      time.Time `json:"passTime" url:"passTime"`
	RangeKm       float64   `json:"rangeKm" url:"rangeKm"`
	SatelliteID   string    `json:"satelliteId" url:"satelliteId"`
	SatelliteName string    `json:"satelliteName" url:"satelliteName"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NextVisiblePassResponse) GetAzimuthDeg() float64 {
	if n == nil {
		return 0
	}
	return n.AzimuthDeg
}

func (n *NextVisiblePassResponse) GetElevationDeg() float64 {
	if n == nil {
		return 0
	}
	return n.ElevationDeg
}

func (n *NextVisiblePassResponse) GetPassTime() time.Time {
	if n == nil {
		return time.Time{}
	}
	return n.PassTime
}

func (n *NextVisiblePassResponse) GetRangeKm() float64 {
	if n == nil {
		return 0
	}
	return n.RangeKm
}

func (n *NextVisiblePassResponse) GetSatelliteID() string {
	if n == nil {
		return ""
	}
	return n.SatelliteID
}

func (n *NextVisiblePassResponse) GetSatelliteName() string {
	if n == nil {
		return ""
	}
	return n.SatelliteName
}

func (n *NextVisiblePassResponse) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NextVisiblePassResponse) require(field *big.Int) {
	next := new(big.Int)
	if n.explicitFields != nil {
		next.Set(n.explicitFields)
	}
	next.Or(next, field)
	n.explicitFields = next
}

// SetAzimuthDeg sets the AzimuthDeg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NextVisiblePassResponse) SetAzimuthDeg(azimuthDeg float64) {
	n.AzimuthDeg = azimuthDeg
	n.require(nextVisiblePassResponseFieldAzimuthDeg)
}

// SetElevationDeg sets the ElevationDeg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NextVisiblePassResponse) SetElevationDeg(elevationDeg float64) {
	n.ElevationDeg = elevationDeg
	n.require(nextVisiblePassResponseFieldElevationDeg)
}

// SetPassTime sets the PassTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NextVisiblePassResponse) SetPassTime(passTime time.Time) {
	n.PassTime = passTime
	n.require(nextVisiblePassResponseFieldPassTime)
}

// SetRangeKm sets the RangeKm field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NextVisiblePassResponse) SetRangeKm(rangeKm float64) {
	n.RangeKm = rangeKm
	n.require(nextVisiblePassResponseFieldRangeKm)
}

// SetSatelliteID sets the SatelliteID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NextVisiblePassResponse) SetSatelliteID(satelliteID string) {
	n.SatelliteID = satelliteID
	n.require(nextVisiblePassResponseFieldSatelliteID)
}

// SetSatelliteName sets the SatelliteName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NextVisiblePassResponse) SetSatelliteName(satelliteName string) {
	n.SatelliteName = satelliteName
	n.require(nextVisiblePassResponseFieldSatelliteName)
}

func (n *NextVisiblePassResponse) UnmarshalJSON(data []byte) error {
	type embed NextVisiblePassResponse
	var unmarshaler = struct {
		embed
		PassTime *internal.DateTime `json:"passTime"`
	}{
		embed: embed(*n),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*n = NextVisiblePassResponse(unmarshaler.embed)
	n.PassTime = unmarshaler.PassTime.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NextVisiblePassResponse) MarshalJSON() ([]byte, error) {
	type embed NextVisiblePassResponse
	var marshaler = struct {
		embed
		PassTime *internal.DateTime `json:"passTime"`
	}{
		embed:    embed(*n),
		PassTime: internal.NewDateTime(n.PassTime),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NextVisiblePassResponse) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	overheadResponseFieldElevation = big.NewInt(1 << 0)
	overheadResponseFieldSatellite = big.NewInt(1 << 1)
)

type OverheadResponse struct {
	Elevation float64    `json:"elevation" url:"elevation"`
	Satellite *Satellite `json:"satellite" url:"satellite"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OverheadResponse) GetElevation() float64 {
	if o == nil {
		return 0
	}
	return o.Elevation
}

func (o *OverheadResponse) GetSatellite() *Satellite {
	if o == nil {
		return nil
	}
	return o.Satellite
}

func (o *OverheadResponse) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *OverheadResponse) require(field *big.Int) {
	next := new(big.Int)
	if o.explicitFields != nil {
		next.Set(o.explicitFields)
	}
	next.Or(next, field)
	o.explicitFields = next
}

// SetElevation sets the Elevation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OverheadResponse) SetElevation(elevation float64) {
	o.Elevation = elevation
	o.require(overheadResponseFieldElevation)
}

// SetSatellite sets the Satellite field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OverheadResponse) SetSatellite(satellite *Satellite) {
	o.Satellite = satellite
	o.require(overheadResponseFieldSatellite)
}

func (o *OverheadResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OverheadResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OverheadResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OverheadResponse) MarshalJSON() ([]byte, error) {
	type embed OverheadResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OverheadResponse) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}
