// Code generated by Fern. DO NOT EDIT.

package api

import (
	core "sdk/core"
	internal "sdk/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	404: func(apiError *core.APIError) error {
		return &NotFoundError{
			APIError: apiError,
		}
	},
	500: func(apiError *core.APIError) error {
		return &InternalServerError{
			APIError: apiError,
		}
	},
	400: func(apiError *core.APIError) error {
		return &BadRequestError{
			APIError: apiError,
		}
	},
}
