// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
)

var (
	triggerPipelineSyncRequestFieldGroup = big.NewInt(1 << 0)
)

type TriggerPipelineSyncRequest struct {
	// CelesTrak satellite group name (e.g. 'stations', 'visual', 'starlink', 'weather', 'active', 'last-30-days')
	Group *string `json:"-" url:"group,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TriggerPipelineSyncRequest) require(field *big.Int) {
	next := new(big.Int)
	if t.explicitFields != nil {
		next.Set(t.explicitFields)
	}
	next.Or(next, field)
	t.explicitFields = next
}

// SetGroup sets the Group field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TriggerPipelineSyncRequest) SetGroup(group *string) {
	t.Group = group
	t.require(triggerPipelineSyncRequestFieldGroup)
}

var (
	pipelineSyncResponseFieldGroup       = big.NewInt(1 << 0)
	pipelineSyncResponseFieldMessage     = big.NewInt(1 << 1)
	pipelineSyncResponseFieldSyncedCount = big.NewInt(1 << 2)
)

type PipelineSyncResponse struct {
	Group       string `json:"group" url:"group"`
	Message     string `json:"message" url:"message"`
	SyncedCount int    `json:"syncedCount" url:"syncedCount"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PipelineSyncResponse) GetGroup() string {
	if p == nil {
		return ""
	}
	return p.Group
}

func (p *PipelineSyncResponse) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}

func (p *PipelineSyncResponse) GetSyncedCount() int {
	if p == nil {
		return 0
	}
	return p.SyncedCount
}

func (p *PipelineSyncResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PipelineSyncResponse) require(field *big.Int) {
	next := new(big.Int)
	if p.explicitFields != nil {
		next.Set(p.explicitFields)
	}
	next.Or(next, field)
	p.explicitFields = next
}

// SetGroup sets the Group field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PipelineSyncResponse) SetGroup(group string) {
	p.Group = group
	p.require(pipelineSyncResponseFieldGroup)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PipelineSyncResponse) SetMessage(message string) {
	p.Message = message
	p.require(pipelineSyncResponseFieldMessage)
}

// SetSyncedCount sets the SyncedCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PipelineSyncResponse) SetSyncedCount(syncedCount int) {
	p.SyncedCount = syncedCount
	p.require(pipelineSyncResponseFieldSyncedCount)
}

func (p *PipelineSyncResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PipelineSyncResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PipelineSyncResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PipelineSyncResponse) MarshalJSON() ([]byte, error) {
	type embed PipelineSyncResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PipelineSyncResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
