// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
)

var (
	createSatelliteDtoFieldLineOne = big.NewInt(1 << 0)
	createSatelliteDtoFieldLineTwo = big.NewInt(1 << 1)
	createSatelliteDtoFieldName    = big.NewInt(1 << 2)
)

type CreateSatelliteDto struct {
	LineOne string `json:"lineOne" url:"-"`
	LineTwo string `json:"lineTwo" url:"-"`
	Name    string `json:"name" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateSatelliteDto) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetLineOne sets the LineOne field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSatelliteDto) SetLineOne(lineOne string) {
	c.LineOne = lineOne
	c.require(createSatelliteDtoFieldLineOne)
}

// SetLineTwo sets the LineTwo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSatelliteDto) SetLineTwo(lineTwo string) {
	c.LineTwo = lineTwo
	c.require(createSatelliteDtoFieldLineTwo)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSatelliteDto) SetName(name string) {
	c.Name = name
	c.require(createSatelliteDtoFieldName)
}

func (c *CreateSatelliteDto) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSatelliteDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateSatelliteDto(body)
	return nil
}

func (c *CreateSatelliteDto) MarshalJSON() ([]byte, error) {
	type embed CreateSatelliteDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteSatelliteRequestFieldID = big.NewInt(1 << 0)
)

type DeleteSatelliteRequest struct {
	// Satellite unique UUID identifier
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteSatelliteRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSatelliteRequest) SetID(id string) {
	d.ID = id
	d.require(deleteSatelliteRequestFieldID)
}

var (
	getSatelliteRequestFieldID = big.NewInt(1 << 0)
)

type GetSatelliteRequest struct {
	// Satellite unique UUID identifier
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetSatelliteRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSatelliteRequest) SetID(id string) {
	g.ID = id
	g.require(getSatelliteRequestFieldID)
}

var (
	listSatellitesRequestFieldLimit  = big.NewInt(1 << 0)
	listSatellitesRequestFieldCursor = big.NewInt(1 << 1)
)

type ListSatellitesRequest struct {
	Limit  *int    `json:"-" url:"limit,omitempty"`
	Cursor *string `json:"-" url:"cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListSatellitesRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSatellitesRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listSatellitesRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSatellitesRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listSatellitesRequestFieldCursor)
}

var (
	paginatedResponseSatelliteFieldData       = big.NewInt(1 << 0)
	paginatedResponseSatelliteFieldPagination = big.NewInt(1 << 1)
)

// Generic Paginated Response envelope
type PaginatedResponseSatellite struct {
	Data       []*Satellite    `json:"data" url:"data"`
	Pagination *PaginationMeta `json:"pagination" url:"pagination"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginatedResponseSatellite) GetData() []*Satellite {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PaginatedResponseSatellite) GetPagination() *PaginationMeta {
	if p == nil {
		return nil
	}
	return p.Pagination
}

func (p *PaginatedResponseSatellite) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PaginatedResponseSatellite) require(field *big.Int) {
	next := new(big.Int)
	if p.explicitFields != nil {
		next.Set(p.explicitFields)
	}
	next.Or(next, field)
	p.explicitFields = next
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseSatellite) SetData(data []*Satellite) {
	p.Data = data
	p.require(paginatedResponseSatelliteFieldData)
}

// SetPagination sets the Pagination field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginatedResponseSatellite) SetPagination(pagination *PaginationMeta) {
	p.Pagination = pagination
	p.require(paginatedResponseSatelliteFieldPagination)
}

func (p *PaginatedResponseSatellite) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginatedResponseSatellite
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginatedResponseSatellite(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginatedResponseSatellite) MarshalJSON() ([]byte, error) {
	type embed PaginatedResponseSatellite
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaginatedResponseSatellite) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	paginationMetaFieldHasMore    = big.NewInt(1 << 0)
	paginationMetaFieldLimit      = big.NewInt(1 << 1)
	paginationMetaFieldNextCursor = big.NewInt(1 << 2)
	paginationMetaFieldTotalCount = big.NewInt(1 << 3)
)

// paginationMetaNullableFields maps the wire names of PaginationMeta's nullable fields (required or optional) to their field bits.
var paginationMetaNullableFields = map[string]*big.Int{
	"nextCursor": paginationMetaFieldNextCursor,
}

// Metadata envelope for paginated responses
type PaginationMeta struct {
	HasMore    bool    `json:"hasMore" url:"hasMore"`
	Limit      int     `json:"limit" url:"limit"`
	NextCursor *string `json:"nextCursor,omitempty" url:"nextCursor,omitempty"`
	TotalCount int     `json:"totalCount" url:"totalCount"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PaginationMeta) GetHasMore() bool {
	if p == nil {
		return false
	}
	return p.HasMore
}

func (p *PaginationMeta) GetLimit() int {
	if p == nil {
		return 0
	}
	return p.Limit
}

func (p *PaginationMeta) GetNextCursor() *string {
	if p == nil {
		return nil
	}
	return p.NextCursor
}

func (p *PaginationMeta) GetTotalCount() int {
	if p == nil {
		return 0
	}
	return p.TotalCount
}

func (p *PaginationMeta) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PaginationMeta) require(field *big.Int) {
	next := new(big.Int)
	if p.explicitFields != nil {
		next.Set(p.explicitFields)
	}
	next.Or(next, field)
	p.explicitFields = next
}

// SetHasMore sets the HasMore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationMeta) SetHasMore(hasMore bool) {
	p.HasMore = hasMore
	p.require(paginationMetaFieldHasMore)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationMeta) SetLimit(limit int) {
	p.Limit = limit
	p.require(paginationMetaFieldLimit)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationMeta) SetNextCursor(nextCursor *string) {
	p.NextCursor = nextCursor
	p.require(paginationMetaFieldNextCursor)
}

// SetTotalCount sets the TotalCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PaginationMeta) SetTotalCount(totalCount int) {
	p.TotalCount = totalCount
	p.require(paginationMetaFieldTotalCount)
}

func (p *PaginationMeta) UnmarshalJSON(data []byte) error {
	type unmarshaler PaginationMeta
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PaginationMeta(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	presentFields, err := internal.ExplicitFieldsFromJSON(data, paginationMetaNullableFields)
	if err != nil {
		return err
	}
	if presentFields != nil {
		p.require(presentFields)
	}
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PaginationMeta) MarshalJSON() ([]byte, error) {
	type embed PaginationMeta
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PaginationMeta) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	updateSatelliteDtoFieldID      = big.NewInt(1 << 0)
	updateSatelliteDtoFieldLineOne = big.NewInt(1 << 1)
	updateSatelliteDtoFieldLineTwo = big.NewInt(1 << 2)
	updateSatelliteDtoFieldName    = big.NewInt(1 << 3)
)

type UpdateSatelliteDto struct {
	// Satellite unique UUID identifier
	ID      string  `json:"-" url:"-"`
	LineOne *string `json:"lineOne,omitempty" url:"-"`
	LineTwo *string `json:"lineTwo,omitempty" url:"-"`
	Name    *string `json:"name,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateSatelliteDto) require(field *big.Int) {
	next := new(big.Int)
	if u.explicitFields != nil {
		next.Set(u.explicitFields)
	}
	next.Or(next, field)
	u.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSatelliteDto) SetID(id string) {
	u.ID = id
	u.require(updateSatelliteDtoFieldID)
}

// SetLineOne sets the LineOne field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSatelliteDto) SetLineOne(lineOne *string) {
	u.LineOne = lineOne
	u.require(updateSatelliteDtoFieldLineOne)
}

// SetLineTwo sets the LineTwo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSatelliteDto) SetLineTwo(lineTwo *string) {
	u.LineTwo = lineTwo
	u.require(updateSatelliteDtoFieldLineTwo)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSatelliteDto) SetName(name *string) {
	u.Name = name
	u.require(updateSatelliteDtoFieldName)
}

func (u *UpdateSatelliteDto) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateSatelliteDto
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateSatelliteDto(body)
	return nil
}

func (u *UpdateSatelliteDto) MarshalJSON() ([]byte, error) {
	type embed UpdateSatelliteDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
