// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
	time "time"
)

var (
	errorResponseFieldError  = big.NewInt(1 << 0)
	errorResponseFieldStatus = big.NewInt(1 << 1)
)

type ErrorResponse struct {
	Error  string `json:"error" url:"error"`
	Status int    `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ErrorResponse) GetError() string {
	if e == nil {
		return ""
	}
	return e.Error
}

func (e *ErrorResponse) GetStatus() int {
	if e == nil {
		return 0
	}
	return e.Status
}

func (e *ErrorResponse) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *ErrorResponse) require(field *big.Int) {
	next := new(big.Int)
	if e.explicitFields != nil {
		next.Set(e.explicitFields)
	}
	next.Or(next, field)
	e.explicitFields = next
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetError(error_ string) {
	e.Error = error_
	e.require(errorResponseFieldError)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetStatus(status int) {
	e.Status = status
	e.require(errorResponseFieldStatus)
}

func (e *ErrorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ErrorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ErrorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ErrorResponse) MarshalJSON() ([]byte, error) {
	type embed ErrorResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ErrorResponse) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	satelliteFieldCreatedDate      = big.NewInt(1 << 0)
	satelliteFieldID               = big.NewInt(1 << 1)
	satelliteFieldLastModifiedDate = big.NewInt(1 << 2)
	satelliteFieldName             = big.NewInt(1 << 3)
	satelliteFieldTle              = big.NewInt(1 << 4)
)

type Satellite struct {
	CreatedDate      time.Time `json:"createdDate" url:"createdDate"`
	ID               string    `json:"id" url:"id"`
	LastModifiedDate time.Time `json:"lastModifiedDate" url:"lastModifiedDate"`
	Name             string    `json:"name" url:"name"`
	Tle              *Tle      `json:"tle" url:"tle"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *Satellite) GetCreatedDate() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedDate
}

func (s *Satellite) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Satellite) GetLastModifiedDate() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.LastModifiedDate
}

func (s *Satellite) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *Satellite) GetTle() *Tle {
	if s == nil {
		return nil
	}
	return s.Tle
}

func (s *Satellite) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *Satellite) require(field *big.Int) {
	next := new(big.Int)
	if s.explicitFields != nil {
		next.Set(s.explicitFields)
	}
	next.Or(next, field)
	s.explicitFields = next
}

// SetCreatedDate sets the CreatedDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Satellite) SetCreatedDate(createdDate time.Time) {
	s.CreatedDate = createdDate
	s.require(satelliteFieldCreatedDate)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Satellite) SetID(id string) {
	s.ID = id
	s.require(satelliteFieldID)
}

// SetLastModifiedDate sets the LastModifiedDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Satellite) SetLastModifiedDate(lastModifiedDate time.Time) {
	s.LastModifiedDate = lastModifiedDate
	s.require(satelliteFieldLastModifiedDate)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Satellite) SetName(name string) {
	s.Name = name
	s.require(satelliteFieldName)
}

// SetTle sets the Tle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *Satellite) SetTle(tle *Tle) {
	s.Tle = tle
	s.require(satelliteFieldTle)
}

func (s *Satellite) UnmarshalJSON(data []byte) error {
	type embed Satellite
	var unmarshaler = struct {
		embed
		CreatedDate      *internal.DateTime `json:"createdDate"`
		LastModifiedDate *internal.DateTime `json:"lastModifiedDate"`
	}{
		embed: embed(*s),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*s = Satellite(unmarshaler.embed)
	s.CreatedDate = unmarshaler.CreatedDate.Time()
	s.LastModifiedDate = unmarshaler.LastModifiedDate.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *Satellite) MarshalJSON() ([]byte, error) {
	type embed Satellite
	var marshaler = struct {
		embed
		CreatedDate      *internal.DateTime `json:"createdDate"`
		LastModifiedDate *internal.DateTime `json:"lastModifiedDate"`
	}{
		embed:            embed(*s),
		CreatedDate:      internal.NewDateTime(s.CreatedDate),
		LastModifiedDate: internal.NewDateTime(s.LastModifiedDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *Satellite) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	tleFieldLineOne = big.NewInt(1 << 0)
	tleFieldLineTwo = big.NewInt(1 << 1)
)

type Tle struct {
	LineOne string `json:"lineOne" url:"lineOne"`
	LineTwo string `json:"lineTwo" url:"lineTwo"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *Tle) GetLineOne() string {
	if t == nil {
		return ""
	}
	return t.LineOne
}

func (t *Tle) GetLineTwo() string {
	if t == nil {
		return ""
	}
	return t.LineTwo
}

func (t *Tle) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *Tle) require(field *big.Int) {
	next := new(big.Int)
	if t.explicitFields != nil {
		next.Set(t.explicitFields)
	}
	next.Or(next, field)
	t.explicitFields = next
}

// SetLineOne sets the LineOne field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Tle) SetLineOne(lineOne string) {
	t.LineOne = lineOne
	t.require(tleFieldLineOne)
}

// SetLineTwo sets the LineTwo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Tle) SetLineTwo(lineTwo string) {
	t.LineTwo = lineTwo
	t.require(tleFieldLineTwo)
}

func (t *Tle) UnmarshalJSON(data []byte) error {
	type unmarshaler Tle
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = Tle(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *Tle) MarshalJSON() ([]byte, error) {
	type embed Tle
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *Tle) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
