// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         lineOne: "lineOne",
 *         lineTwo: "lineTwo",
 *         name: "name"
 *     }
 */
export interface CreateSatelliteDto {
    lineOne: string;
    lineTwo: string;
    name: string;
}
