// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DeleteSatelliteRequest {
    /** Satellite unique UUID identifier */
    id: string;
}
