// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateSatelliteDto {
    /** Satellite unique UUID identifier */
    id: string;
    lineOne?: string | null;
    lineTwo?: string | null;
    name?: string | null;
}
