# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.next_visible_pass_response import NextVisiblePassResponse
from ..types.overhead_response import OverheadResponse
from .raw_client import AsyncRawAstrodynamicsClient, RawAstrodynamicsClient


class AstrodynamicsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAstrodynamicsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAstrodynamicsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAstrodynamicsClient
        """
        return self._raw_client

    def get_overhead_satellite(
        self,
        *,
        lat: float,
        lon: float,
        alt: typing.Optional[float] = None,
        time: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OverheadResponse:
        """
        Computes the satellite closest to overhead (highest elevation) across all tracked satellites using parallel Rayon propagation.

        Parameters
        ----------
        lat : float
            Observer latitude in decimal degrees (-90.0 to 90.0)

        lon : float
            Observer longitude in decimal degrees (-180.0 to 180.0)

        alt : typing.Optional[float]
            Observer altitude above sea level in meters

        time : typing.Optional[dt.datetime]
            UTC timestamp for calculation epoch (defaults to current time if omitted)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OverheadResponse
            Overhead satellite computed successfully

        Examples
        --------
        from satellite_api import SatelliteApiApi

        client = SatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.astrodynamics.get_overhead_satellite(
            lat=1.1,
            lon=1.1,
        )
        """
        _response = self._raw_client.get_overhead_satellite(
            lat=lat, lon=lon, alt=alt, time=time, request_options=request_options
        )
        return _response.data

    def get_next_visible_pass(
        self,
        id: str,
        *,
        lat: float,
        lon: float,
        alt: typing.Optional[float] = None,
        threshold_deg: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> NextVisiblePassResponse:
        """
        Calculates the next visible pass for a specific satellite above elevation threshold.

        Parameters
        ----------
        id : str
            Satellite unique UUID identifier

        lat : float
            Observer latitude in decimal degrees (-90.0 to 90.0)

        lon : float
            Observer longitude in decimal degrees (-180.0 to 180.0)

        alt : typing.Optional[float]
            Observer altitude above sea level in meters

        threshold_deg : typing.Optional[float]
            Minimum elevation angle threshold in degrees (default: 5.0 deg)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        NextVisiblePassResponse
            Next visible pass calculated successfully

        Examples
        --------
        from satellite_api import SatelliteApiApi

        client = SatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.astrodynamics.get_next_visible_pass(
            id="id",
            lat=1.1,
            lon=1.1,
        )
        """
        _response = self._raw_client.get_next_visible_pass(
            id, lat=lat, lon=lon, alt=alt, threshold_deg=threshold_deg, request_options=request_options
        )
        return _response.data


class AsyncAstrodynamicsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAstrodynamicsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAstrodynamicsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAstrodynamicsClient
        """
        return self._raw_client

    async def get_overhead_satellite(
        self,
        *,
        lat: float,
        lon: float,
        alt: typing.Optional[float] = None,
        time: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OverheadResponse:
        """
        Computes the satellite closest to overhead (highest elevation) across all tracked satellites using parallel Rayon propagation.

        Parameters
        ----------
        lat : float
            Observer latitude in decimal degrees (-90.0 to 90.0)

        lon : float
            Observer longitude in decimal degrees (-180.0 to 180.0)

        alt : typing.Optional[float]
            Observer altitude above sea level in meters

        time : typing.Optional[dt.datetime]
            UTC timestamp for calculation epoch (defaults to current time if omitted)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OverheadResponse
            Overhead satellite computed successfully

        Examples
        --------
        import asyncio

        from satellite_api import AsyncSatelliteApiApi

        client = AsyncSatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.astrodynamics.get_overhead_satellite(
                lat=1.1,
                lon=1.1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_overhead_satellite(
            lat=lat, lon=lon, alt=alt, time=time, request_options=request_options
        )
        return _response.data

    async def get_next_visible_pass(
        self,
        id: str,
        *,
        lat: float,
        lon: float,
        alt: typing.Optional[float] = None,
        threshold_deg: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> NextVisiblePassResponse:
        """
        Calculates the next visible pass for a specific satellite above elevation threshold.

        Parameters
        ----------
        id : str
            Satellite unique UUID identifier

        lat : float
            Observer latitude in decimal degrees (-90.0 to 90.0)

        lon : float
            Observer longitude in decimal degrees (-180.0 to 180.0)

        alt : typing.Optional[float]
            Observer altitude above sea level in meters

        threshold_deg : typing.Optional[float]
            Minimum elevation angle threshold in degrees (default: 5.0 deg)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        NextVisiblePassResponse
            Next visible pass calculated successfully

        Examples
        --------
        import asyncio

        from satellite_api import AsyncSatelliteApiApi

        client = AsyncSatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.astrodynamics.get_next_visible_pass(
                id="id",
                lat=1.1,
                lon=1.1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_next_visible_pass(
            id, lat=lat, lon=lon, alt=alt, threshold_deg=threshold_deg, request_options=request_options
        )
        return _response.data
