# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.datetime_utils import serialize_datetime
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.not_found_error import NotFoundError
from ..types.error_response import ErrorResponse
from ..types.next_visible_pass_response import NextVisiblePassResponse
from ..types.overhead_response import OverheadResponse
from pydantic import ValidationError


class RawAstrodynamicsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_overhead_satellite(
        self,
        *,
        lat: float,
        lon: float,
        alt: typing.Optional[float] = None,
        time: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OverheadResponse]:
        """
        Computes the satellite closest to overhead (highest elevation) across all tracked satellites using parallel Rayon propagation.

        Parameters
        ----------
        lat : float
            Observer latitude in decimal degrees (-90.0 to 90.0)

        lon : float
            Observer longitude in decimal degrees (-180.0 to 180.0)

        alt : typing.Optional[float]
            Observer altitude above sea level in meters

        time : typing.Optional[dt.datetime]
            UTC timestamp for calculation epoch (defaults to current time if omitted)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OverheadResponse]
            Overhead satellite computed successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/astrodynamics/overhead",
            method="GET",
            params={
                "lat": lat,
                "lon": lon,
                "alt": alt,
                "time": serialize_datetime(time) if time is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OverheadResponse,
                    parse_obj_as(
                        type_=OverheadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_next_visible_pass(
        self,
        id: str,
        *,
        lat: float,
        lon: float,
        alt: typing.Optional[float] = None,
        threshold_deg: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[NextVisiblePassResponse]:
        """
        Calculates the next visible pass for a specific satellite above elevation threshold.

        Parameters
        ----------
        id : str
            Satellite unique UUID identifier

        lat : float
            Observer latitude in decimal degrees (-90.0 to 90.0)

        lon : float
            Observer longitude in decimal degrees (-180.0 to 180.0)

        alt : typing.Optional[float]
            Observer altitude above sea level in meters

        threshold_deg : typing.Optional[float]
            Minimum elevation angle threshold in degrees (default: 5.0 deg)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[NextVisiblePassResponse]
            Next visible pass calculated successfully
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/satellites/{encode_path_param(id)}/next-visible",
            method="GET",
            params={
                "lat": lat,
                "lon": lon,
                "alt": alt,
                "threshold_deg": threshold_deg,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    NextVisiblePassResponse,
                    parse_obj_as(
                        type_=NextVisiblePassResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAstrodynamicsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_overhead_satellite(
        self,
        *,
        lat: float,
        lon: float,
        alt: typing.Optional[float] = None,
        time: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OverheadResponse]:
        """
        Computes the satellite closest to overhead (highest elevation) across all tracked satellites using parallel Rayon propagation.

        Parameters
        ----------
        lat : float
            Observer latitude in decimal degrees (-90.0 to 90.0)

        lon : float
            Observer longitude in decimal degrees (-180.0 to 180.0)

        alt : typing.Optional[float]
            Observer altitude above sea level in meters

        time : typing.Optional[dt.datetime]
            UTC timestamp for calculation epoch (defaults to current time if omitted)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OverheadResponse]
            Overhead satellite computed successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/astrodynamics/overhead",
            method="GET",
            params={
                "lat": lat,
                "lon": lon,
                "alt": alt,
                "time": serialize_datetime(time) if time is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OverheadResponse,
                    parse_obj_as(
                        type_=OverheadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_next_visible_pass(
        self,
        id: str,
        *,
        lat: float,
        lon: float,
        alt: typing.Optional[float] = None,
        threshold_deg: typing.Optional[float] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[NextVisiblePassResponse]:
        """
        Calculates the next visible pass for a specific satellite above elevation threshold.

        Parameters
        ----------
        id : str
            Satellite unique UUID identifier

        lat : float
            Observer latitude in decimal degrees (-90.0 to 90.0)

        lon : float
            Observer longitude in decimal degrees (-180.0 to 180.0)

        alt : typing.Optional[float]
            Observer altitude above sea level in meters

        threshold_deg : typing.Optional[float]
            Minimum elevation angle threshold in degrees (default: 5.0 deg)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[NextVisiblePassResponse]
            Next visible pass calculated successfully
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/satellites/{encode_path_param(id)}/next-visible",
            method="GET",
            params={
                "lat": lat,
                "lon": lon,
                "alt": alt,
                "threshold_deg": threshold_deg,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    NextVisiblePassResponse,
                    parse_obj_as(
                        type_=NextVisiblePassResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
