# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.paginated_response_satellite import PaginatedResponseSatellite
from ..types.satellite import Satellite
from .raw_client import AsyncRawSatellitesClient, RawSatellitesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SatellitesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSatellitesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSatellitesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSatellitesClient
        """
        return self._raw_client

    def list_satellites(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseSatellite:
        """
        Retrieves a paginated list of satellites using base64 checkpoint cursors.

        Parameters
        ----------
        limit : typing.Optional[int]

        cursor : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseSatellite
            Paginated list of satellites

        Examples
        --------
        from satellite_api import SatelliteApiApi

        client = SatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.satellites.list_satellites()
        """
        _response = self._raw_client.list_satellites(limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    def create_satellite(
        self, *, line_one: str, line_two: str, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Satellite:
        """
        Creates a new satellite record from Two-Line Element (TLE) set data.

        Parameters
        ----------
        line_one : str

        line_two : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Satellite
            Satellite created successfully

        Examples
        --------
        from satellite_api import SatelliteApiApi

        client = SatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.satellites.create_satellite(
            line_one="lineOne",
            line_two="lineTwo",
            name="name",
        )
        """
        _response = self._raw_client.create_satellite(
            line_one=line_one, line_two=line_two, name=name, request_options=request_options
        )
        return _response.data

    def get_satellite(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Satellite:
        """
        Retrieves details for a specific satellite by its unique UUID.

        Parameters
        ----------
        id : str
            Satellite unique UUID identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Satellite
            Satellite found

        Examples
        --------
        from satellite_api import SatelliteApiApi

        client = SatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.satellites.get_satellite(
            id="id",
        )
        """
        _response = self._raw_client.get_satellite(id, request_options=request_options)
        return _response.data

    def delete_satellite(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Deletes a satellite record by its unique UUID.

        Parameters
        ----------
        id : str
            Satellite unique UUID identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from satellite_api import SatelliteApiApi

        client = SatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.satellites.delete_satellite(
            id="id",
        )
        """
        _response = self._raw_client.delete_satellite(id, request_options=request_options)
        return _response.data

    def update_satellite(
        self,
        id: str,
        *,
        line_one: typing.Optional[str] = OMIT,
        line_two: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Satellite:
        """
        Updates a satellite's name or TLE orbital parameters.

        Parameters
        ----------
        id : str
            Satellite unique UUID identifier

        line_one : typing.Optional[str]

        line_two : typing.Optional[str]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Satellite
            Satellite updated successfully

        Examples
        --------
        from satellite_api import SatelliteApiApi

        client = SatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.satellites.update_satellite(
            id="id",
        )
        """
        _response = self._raw_client.update_satellite(
            id, line_one=line_one, line_two=line_two, name=name, request_options=request_options
        )
        return _response.data


class AsyncSatellitesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSatellitesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSatellitesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSatellitesClient
        """
        return self._raw_client

    async def list_satellites(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaginatedResponseSatellite:
        """
        Retrieves a paginated list of satellites using base64 checkpoint cursors.

        Parameters
        ----------
        limit : typing.Optional[int]

        cursor : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaginatedResponseSatellite
            Paginated list of satellites

        Examples
        --------
        import asyncio

        from satellite_api import AsyncSatelliteApiApi

        client = AsyncSatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.satellites.list_satellites()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_satellites(limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    async def create_satellite(
        self, *, line_one: str, line_two: str, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Satellite:
        """
        Creates a new satellite record from Two-Line Element (TLE) set data.

        Parameters
        ----------
        line_one : str

        line_two : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Satellite
            Satellite created successfully

        Examples
        --------
        import asyncio

        from satellite_api import AsyncSatelliteApiApi

        client = AsyncSatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.satellites.create_satellite(
                line_one="lineOne",
                line_two="lineTwo",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_satellite(
            line_one=line_one, line_two=line_two, name=name, request_options=request_options
        )
        return _response.data

    async def get_satellite(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Satellite:
        """
        Retrieves details for a specific satellite by its unique UUID.

        Parameters
        ----------
        id : str
            Satellite unique UUID identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Satellite
            Satellite found

        Examples
        --------
        import asyncio

        from satellite_api import AsyncSatelliteApiApi

        client = AsyncSatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.satellites.get_satellite(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_satellite(id, request_options=request_options)
        return _response.data

    async def delete_satellite(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Deletes a satellite record by its unique UUID.

        Parameters
        ----------
        id : str
            Satellite unique UUID identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from satellite_api import AsyncSatelliteApiApi

        client = AsyncSatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.satellites.delete_satellite(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_satellite(id, request_options=request_options)
        return _response.data

    async def update_satellite(
        self,
        id: str,
        *,
        line_one: typing.Optional[str] = OMIT,
        line_two: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Satellite:
        """
        Updates a satellite's name or TLE orbital parameters.

        Parameters
        ----------
        id : str
            Satellite unique UUID identifier

        line_one : typing.Optional[str]

        line_two : typing.Optional[str]

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Satellite
            Satellite updated successfully

        Examples
        --------
        import asyncio

        from satellite_api import AsyncSatelliteApiApi

        client = AsyncSatelliteApiApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.satellites.update_satellite(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_satellite(
            id, line_one=line_one, line_two=line_two, name=name, request_options=request_options
        )
        return _response.data
