// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         lat: 1.1,
 *         lon: 1.1
 *     }
 */
export interface GetNextVisiblePassRequest {
    /** Satellite unique UUID identifier */
    id: string;
    /** Observer latitude in decimal degrees (-90.0 to 90.0) */
    lat: number;
    /** Observer longitude in decimal degrees (-180.0 to 180.0) */
    lon: number;
    /** Observer altitude above sea level in meters */
    alt?: number | null;
    /** Minimum elevation angle threshold in degrees (default: 5.0 deg) */
    threshold_deg?: number | null;
}
