// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         lat: 1.1,
 *         lon: 1.1
 *     }
 */
export interface GetOverheadSatelliteRequest {
    /** Observer latitude in decimal degrees (-90.0 to 90.0) */
    lat: number;
    /** Observer longitude in decimal degrees (-180.0 to 180.0) */
    lon: number;
    /** Observer altitude above sea level in meters */
    alt?: number | null;
    /** UTC timestamp for calculation epoch (defaults to current time if omitted) */
    time?: string | null;
}
